Outfits view
uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app pull request #146
Opened 2024-04-21 21:01 UTC by Cristina-Figueroa

1) Fixed the render issue, ya se puede ver en Android.
2) Overall styling of Outfits Main Page, Edit page and Make Your Outfit page, falta la logica

2024-04-21 21:57 UTC, Adhel-Esteban1 requested changes
Hi, Cristina. I reviewed the code, and tested it on android it works fine. On iOS there's a bit of trouble with the styles though. But I suggest a big change, even bigger than restyle for iOS. Reading and implementing code for over 500 lines and filtering what is necessary and unnecessary is a complicated task. I suggest a refactor of the 3 changed files: outfits.tsx, addOutift.tsx, and edit.tsx. 

There are unused imports, unused functions, constants, commented code, and more. This makes the code very difficult to review, and understand what's going on.

Here's a plan idea. I managed to shorten the 500+ line code of outfits.tsx file into a simple and easy-to-read 45-line code on the branch 120-seamless-design. Right now there's a PR for that branch under review, and we can merge that one first. Then, I can help out in the refactoring of the 3 files I mentioned.

2024-04-22 03:04 UTC, Cristina-Figueroa commented
Hi Adhel! I've done the refactoring you've requested for the three outfit files, outfits.tsx, addOutfit.tsx, and edit.tsx. Right now addOutfit.tsx and edit.tsx average on 230 lines of code, while outfits.tsx has about 180 lines of code. I've created about 7 files of components used by all three files. They are located under the components folder of the project. 

Right now, there's only styling for android version of the app, which means I'm still gonna need help styling the iOS part for the outfits screens/pages. Other than that, we can start working on the implementation of features as well as add your part of the MainOutfit page.

Let me know if you need any help understanding the code!

2024-04-23 02:18 UTC, Adhel-Esteban1 requested changes
Most of the changes I suggest is removing commented code, and some unused imports. I learned this recently and it really helps for other developers. 

I think using the components for buttons like cancel and more is a very good idea. However, I think it may have been a little overdone. I think perhaps the entire lower square could've been a component, and likewise, restyle the existing filter component and use that component on the top filters. Seamless design can fix this later though. 

Other than that, the code is much more readable. I think the many components was overdone as it's not looking good on iOS, but that can be fixed later. The foundation is set for future development. 

Just check out the comments on unused imports and commented code, and that should be good to go.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/EditOutfitButton.tsx
> +            // onPress={() => setModalVisible(true)}
Commented code. But I'm unsure if it's necessary.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitsFilterBoxes.tsx
> +    // backgroundColor: 'lightblue',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitsFilterBoxes.tsx
> +          // top:5
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitsFilterBoxes.tsx
> +    // backgroundColor: 'pink',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitsFilterBoxes.tsx
> +    // backgroundColor: 'black', //ffff
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitButton.tsx
> +        // backgroundColor: 'lightblue',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/OutfitButton.tsx
> +import { Pressable, StyleSheet, Platform,} from 'react-native';
Unused import can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/NameOfOutfitPlaceholder.tsx
Perhaps the entire lower part that houses the buttons and the rectangle can be a single component.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/EditOutfitButton.tsx
> +            backgroundColor: '#F0F0F0' //'#F194FF'
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on components/EditOutfitButton.tsx
> +
Unused import can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +        // top: 0,
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +        backgroundColor: '#F0F0F0' ,//'#D9D9D9'
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +            // },
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +                // height: "120%",
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +        // backgroundColor: 'pink',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +        // backgroundColor: 'pink',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/addOutfit.tsx
> +        // backgroundColor: 'black',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/(tabs)/outfits.tsx
> +    // backgroundColor: 'lightblue',
Commented code can be removed.

2024-04-23 02:18 UTC, Adhel-Esteban1 commented on app/(tabs)/outfits.tsx
> +    // backgroundColor: 'lightblue',
Commented code can be removed.

2024-04-26 19:57 UTC, Adhel-Esteban1 approved these changes
Very well done! Much better now! And much easier to read as well!

2024-04-26 22:18 UTC, merged